### PR TITLE
Fixes to support Python 3

### PR DESCRIPTION
**Pull request by andrewmwhite**

### CODE REVIEW

**Comment by terrycojones** [comment]
Thanks Andrew, that's really great / nice of you. Terry.

**Comment by andrewmwhite** [comment]
No problem.

Any chance of an update to PyPI?

**Comment by terrycojones** [comment]
Yes, done, thanks again. I added an `AUTHORS` file and put you in it :-)

**Comment by andrewmwhite** [comment]
Awesome, thanks!

**Pull request merged**
